### ISSUE TITLE
JSON Unexpected End, Bolt v3, Cannot Install

### ISSUE THREAD

**Issue by brysont** [GawainLynch/bolt-extension-nginx-cache-helper#1]
Installed Bolt v3.0.0, installed this extension, received an error for expected end of JOSN input. http://prntscr.com/b3munv

After that error, the entire site crashed on an internal server error. Not seeing another way, I deleted the extension folder via FTP and regained access and functionality for the site, but then there was a notice on every page of the admin that couldn't be dismissed beyond the current page:
```Extension package bolt/nginxcachehelper has an invalid class 'Bolt\Extension\Bolt\NginxCacheHelper\NginxCacheHelperExtension' and has been skipped.```

Sahassar told me where to go fix that part, but sending the issue to you at his suggestion with some server info.

My server is a D.O. VPS running PHP7.0.6-1~dotdeb+8.1 and MySQL 5.6. Linux, Apache, Nginx, Varnish (disabled for the app at this time tho). In case any of that is useful.

**Comment by GawainLynch** [comment]
Yeah, I actually only updated the `composer.json` on that one as I needed a rather unused one to test with when we were writing the v3 extension interface.

Also, that JSON error you got will be properly reported in Bolt 3.0.1 as I fixed it yesterday :laughing: 

All this aside, I'll have a look in the morning and if I have time I'll fix it up properly.

**Comment by GawainLynch** [comment]
Re-tagged a working version for Bolt 3 just now
